name: Build and Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build JAR with Maven
        run: mvn clean package
        env:
          MAVEN_OPTS: "-Dmaven.compiler.release=22"

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: cerdik-jar
          path: target/cerdik_mkpl-1.1-SNAPSHOT.jar
